/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package latihan1;

/**
 *
 * @author Faras
 */
public class boidata extends javax.swing.JFrame {

    /** Creates new form boidata */
    public boidata(String nama, String absen, String Kelas, String Jurusan, String Alamat) {
        String nm, abs, jur, almt;
        String kelas = combo.getSelectedItem().toString();
        nm = idnama.getText();
        abs = idabsen.getText();
        almt = idalamat.getText();
        //jurusan
        if (rdbrpl.isSelected()){
            jur = "RPL";
        }
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idnama = new javax.swing.JLabel();
        idabsen = new javax.swing.JLabel();
        idkelas = new javax.swing.JLabel();
        idjurusan = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        tfabsen = new javax.swing.JTextField();
        tfalamat = new javax.swing.JTextField();
        idalamat = new javax.swing.JLabel();
        rdbrpl = new javax.swing.JRadioButton();
        rdbtkj = new javax.swing.JRadioButton();
        submitbutton = new javax.swing.JButton();
        exitbutton = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel1.setText("BIODATA SISWA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 50, 180, 20);

        idnama.setText("NAMA");
        getContentPane().add(idnama);
        idnama.setBounds(60, 110, 29, 14);

        idabsen.setText("ABSEN");
        getContentPane().add(idabsen);
        idabsen.setBounds(60, 150, 40, 20);

        idkelas.setText("KELAS");
        getContentPane().add(idkelas);
        idkelas.setBounds(60, 194, 60, 30);

        idjurusan.setText("JURUSAN");
        getContentPane().add(idjurusan);
        idjurusan.setBounds(60, 250, 60, 20);

        tfnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnamaActionPerformed(evt);
            }
        });
        getContentPane().add(tfnama);
        tfnama.setBounds(130, 110, 210, 20);
        getContentPane().add(tfabsen);
        tfabsen.setBounds(130, 150, 210, 20);
        getContentPane().add(tfalamat);
        tfalamat.setBounds(130, 290, 210, 20);

        idalamat.setText("ALAMAT");
        getContentPane().add(idalamat);
        idalamat.setBounds(60, 290, 40, 14);

        rdbrpl.setText("RPL");
        getContentPane().add(rdbrpl);
        rdbrpl.setBounds(130, 250, 43, 23);

        rdbtkj.setText("TKJ");
        getContentPane().add(rdbtkj);
        rdbtkj.setBounds(240, 250, 43, 23);

        submitbutton.setText("SUBMIT");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(submitbutton);
        submitbutton.setBounds(360, 210, 70, 23);

        exitbutton.setText("EXIT");
        getContentPane().add(exitbutton);
        exitbutton.setBounds(360, 240, 70, 23);

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XR1", "XR2", "XR3", "XR4", "XR5", "XR6", "XR7", "XT1", "XT2", "XT3", "XT4", "XT5", "XT6" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        getContentPane().add(combo);
        combo.setBounds(130, 200, 60, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void tfnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnamaActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitbuttonActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(boidata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(boidata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(boidata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(boidata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JButton exitbutton;
    private javax.swing.JLabel idabsen;
    private javax.swing.JLabel idalamat;
    private javax.swing.JLabel idjurusan;
    private javax.swing.JLabel idkelas;
    private javax.swing.JLabel idnama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rdbrpl;
    private javax.swing.JRadioButton rdbtkj;
    private javax.swing.JButton submitbutton;
    private javax.swing.JTextField tfabsen;
    private javax.swing.JTextField tfalamat;
    private javax.swing.JTextField tfnama;
    // End of variables declaration//GEN-END:variables

}
