/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan1;

/**
 *
 * @author Faras
 */
public class latihan2 extends javax.swing.JFrame {

    /**
     * Creates new form latihan2
     */
    public latihan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        PilihanJurusan = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        absen = new javax.swing.JLabel();
        jurusan = new javax.swing.JLabel();
        hobi = new javax.swing.JLabel();
        rdbRPL = new javax.swing.JRadioButton();
        rdbTKJ = new javax.swing.JRadioButton();
        varNama = new javax.swing.JTextField();
        varAbsen = new javax.swing.JTextField();
        cbProgram = new javax.swing.JCheckBox();
        cbDesign = new javax.swing.JCheckBox();
        cbAnimation = new javax.swing.JCheckBox();
        cbVE = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAHasil = new javax.swing.JTextArea();
        buttonSubmit = new javax.swing.JButton();
        buttonRemove = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        combo = new javax.swing.JComboBox<>();
        kelas = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\3e848f275ba9f4398c1527a1c63365e2.jpg")); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("BIODATA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 50, 50, 30);

        nama.setText("nama");
        getContentPane().add(nama);
        nama.setBounds(130, 100, 26, 14);

        absen.setText("absen");
        getContentPane().add(absen);
        absen.setBounds(130, 130, 29, 14);

        jurusan.setText("jurusan");
        getContentPane().add(jurusan);
        jurusan.setBounds(130, 160, 50, 14);

        hobi.setText("hobi");
        getContentPane().add(hobi);
        hobi.setBounds(130, 180, 20, 14);

        rdbRPL.setText("RPL");
        getContentPane().add(rdbRPL);
        rdbRPL.setBounds(200, 160, 43, 23);

        rdbTKJ.setText("TKJ");
        getContentPane().add(rdbTKJ);
        rdbTKJ.setBounds(310, 160, 43, 23);

        varNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varNamaActionPerformed(evt);
            }
        });
        getContentPane().add(varNama);
        varNama.setBounds(200, 100, 230, 20);

        varAbsen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varAbsenActionPerformed(evt);
            }
        });
        getContentPane().add(varAbsen);
        varAbsen.setBounds(200, 130, 230, 20);

        cbProgram.setText("Programming");
        getContentPane().add(cbProgram);
        cbProgram.setBounds(200, 180, 90, 23);

        cbDesign.setText("Designer");
        getContentPane().add(cbDesign);
        cbDesign.setBounds(200, 200, 67, 23);

        cbAnimation.setText("Animator");
        getContentPane().add(cbAnimation);
        cbAnimation.setBounds(310, 180, 69, 23);

        cbVE.setText("Video Editing");
        getContentPane().add(cbVE);
        cbVE.setBounds(310, 200, 100, 23);

        TAHasil.setColumns(20);
        TAHasil.setRows(5);
        jScrollPane1.setViewportView(TAHasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(380, 230, 166, 96);

        buttonSubmit.setText("Submit");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSubmit);
        buttonSubmit.setBounds(130, 230, 65, 23);

        buttonRemove.setText("Remove");
        buttonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(buttonRemove);
        buttonRemove.setBounds(220, 230, 71, 23);

        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        getContentPane().add(buttonExit);
        buttonExit.setBounds(310, 230, 51, 23);

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XR1", "XR2", "XR3", "XR4", "XR5", "XR6", "XR7", "XT1", "XT2", "XT3", "XT4", "XT5", "XT6" }));
        getContentPane().add(combo);
        combo.setBounds(210, 270, 44, 20);

        kelas.setText("kelas");
        getContentPane().add(kelas);
        kelas.setBounds(130, 270, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void varAbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varAbsenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varAbsenActionPerformed

    private void varNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varNamaActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveActionPerformed
        // TODO add your handling code here:
        nama.setText("");
        absen.setText("");
        cbProgram.setSelected(false);
        cbDesign.setSelected(false);
        cbAnimation.setSelected(false);
        cbVE.setSelected(false);
    }//GEN-LAST:event_buttonRemoveActionPerformed

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        // TODO add your handling code here:
        String nama = varNama.getText();
        String absen = varAbsen.getText();
        String jurusan;
        String hobi = ("");
        
        //Untuk pilihan jurusan
        if (rdbRPL.isSelected()){
            jurusan = "RPL";
            if(combo.getSelectedItem()=="XR1"){
            }
            if(combo.getSelectedItem()=="XR2"){
            }
            if(combo.getSelectedItem()=="XR3"){
            }
            if(combo.getSelectedItem()=="XR4"){
            }
            if(combo.getSelectedItem()=="XR5"){
            }
            if(combo.getSelectedItem()=="XR6"){
            }
            if(combo.getSelectedItem()=="XR7"){
            }
        }else if(rdbTKJ.isSelected()){
            jurusan = "TKJ";
            if (combo.getSelectedItem()=="XT1"){
            }
            if (combo.getSelectedItem()=="XT2"){
            }
            if (combo.getSelectedItem()=="XT3"){
            }
            if (combo.getSelectedItem()=="XT4"){
            }
            if (combo.getSelectedItem()=="XT5"){
            }
            if (combo.getSelectedItem()=="XT6"){
            }
        }else jurusan = "";{
        //untuk pilihan checkbox
        if (cbProgram.isSelected())
            hobi+=cbProgram.getText()+ ", ";
        
        if (cbDesign.isSelected())
            hobi+=cbDesign.getText()+ ", ";
        
        if (cbAnimation.isSelected())
            hobi+=cbAnimation.getText()+ ", ";
        
        if (cbVE.isSelected())
            hobi+=cbVE.getText()+ ", ";
        
        //untuk hasil
        TAHasil.setText("Nama anda: " + nama + "\nAbsen anda: " + absen + "\nJurusan anda: " + jurusan + "\nHobi anda: " + hobi);
    }//GEN-LAST:event_buttonSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new latihan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup PilihanJurusan;
    private javax.swing.JTextArea TAHasil;
    private javax.swing.JLabel absen;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonRemove;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JCheckBox cbAnimation;
    private javax.swing.JCheckBox cbDesign;
    private javax.swing.JCheckBox cbProgram;
    private javax.swing.JCheckBox cbVE;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel hobi;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jurusan;
    private javax.swing.JLabel kelas;
    private javax.swing.JLabel nama;
    private javax.swing.JRadioButton rdbRPL;
    private javax.swing.JRadioButton rdbTKJ;
    private javax.swing.JTextField varAbsen;
    private javax.swing.JTextField varNama;
    // End of variables declaration//GEN-END:variables
}
